In [2]:
import numpy as np
# Sizes of the state/action spaces
nbS, nbA = 18, 9
#Plant_locations = ['l_1', 'l_2', 'l_3', 'l_4', 'l_5', 'l_6', 'l_7', 'l_8', 'l_9',\
#                 'l_10', 'l_11', 'l_12', 'l_13', 'l_14', 'l_15', 'l_16', 'l_17', 'l_18']
Plant_locations = ['l_1','l_2']
Tool = ['nothing','Watering_nozzle', 'Soil_sensor']
# Actions

#actions = ['water_1', 'water_2','water_3', 'water_4', 'water_5','water_6','water_7','water_8','water_9'\
#         'water_10','water_11','water_12','water_13','water_14','water_15','water_16','water_17','water_18'\
#         'sense_1', 'sense_2','sense_3', 'sense_4', 'sense_5','sense_6','sense_7','sense_8','sense_9'\
#        'sense_10','sense_11','sense_12','sense_13','sense_14','sense_15','sense_16','sense_17','sense_18'\
#       'go_1', 'go_2','go_3', 'go_4', 'go_5','go_6','go_7','go_8','go_9'\
#      'go_10','go_11','go_12','go_13','go_14','go_15','go_16','go_17','go_18'\
#     'unmount','mount_water','mount_Soil_sensor']

actions = ['water_1','water_2','sense_1', 'sense_2','go_1', 'go_2','unmount','mount_water','mount_Soil_sensor']


# Transition matrices dims = (action, current state, next state)
T = np.zeros((nbA, nbS, nbS))
print(T.shape)

# Reward vectors dims = (action, state)
R = np.zeros((nbA, nbS))


def prob_Lj(lj,li,a):
    if a == 4:
        if lj == 0:
            return 1
        else:
            return 0
    else:
        if a == 5:
            if lj == 1:
                return 1
            else:
                return 0
        else:
            if li == lj:
                return 1
            else:
                return 0

def prob_Tj(tj,ti,a):
    if a == 6:
        if tj== 0:
            return 1
        else:
            return 0
    else:
        if a == 7:
            if tj == 1:
                return 1
            else:
                return 0
        else:
            if a == 8:
                if tj == 2:
                    return 1
                else:
                    return 0
            else:
                if tj == ti:
                    return 1
                else:
                    return 0

#action sense_i :
#prob ( m_i' = high | m_i=unknown, sense_i ) = 0.1
#prob ( m_i' = low | m_i=unknown, sense_i ) = 0.9
#prob ( m_i' = unknown | m_i=unknown, sense_i ) = 0

def prob_Mj(mj,li,ti,mi,a):
    if a == 2 and mi ==0 :
        if mj == 2:
            return 0.1
        else:
            if mj == 1:
                return 0.9
            else:
                return 0
    else:
        if a == 0 and ti == 1 and li == 0:
            if mj == 2:
                return 1
            else:
                return 0
        else:
            if a == 1 and ti == 1 and li == 1:
                if mj == 2:
                    return 1
                else:
                    return 0
            
            else:
                if mj == mi:
                    return 1
                else:
                    return 0
            
ligne = 0
colonne  = 0
for a in range(nbA):
    ligne = 0
    for li in range(2):
        for ti in range(3):
            for mi in range(3):
                colonne = 0
                for lj in range(2):
                    for tj in range(3):
                        for mj in range(3):
                            T[a,ligne,colonne] = prob_Lj(lj,li,a)*prob_Tj(tj,ti,a)*prob_Mj(mj,li,ti,mi,a)
                            #if lj == 0 and li == 0 and a == 0 and tj == 0 and ti == 0 and mj == 2 and mi == 2:
                                #print(ligne)
                               # print(colonne)
                            #if a == 0 and ti == 1 and li == 0:
                                #print(ligne)
                            colonne = colonne + 1
                ligne = ligne + 1
                            
            

R[0,2] = 10 #recompense
R[1,8] = 10 #recompense
moving = -4
for i in range(nbS-1):
    R[6,i] = -5 # un cout pour les tools
    R[7,i] = -5 # un cout pour les tools
    R[8,i] = -5 # un cout pour les tools
    if i>5:
        R[5,i] = moving # un cout pour se deplacer
    if i<6:
        R[4,i] = moving # un cout pour se deplacer

# Check that the transition matrix contains probability distributions
print('\n-- Check the transition function --')
#action_names = ['a','b']
#action_names = ['go_right','return  ']
action_names = ['water_1','water_2','sense_1', 'sense_2','go_1', 'go_2','unmount','mount_water','mount_Soil_sensor']

for a in range(9):
    if np.any(np.sum(T[a,:,:],axis=1)==np.ones(nbS)):
        print('transition matrix for action <', action_names[a], '> (normalized).')
        print(T[a,:,:])
    else:
        print('WARNING: transition matrix of action <', action_names[a], '> is NOT normalized.')
        print(T[a,:,:])
    
# Print reward vectors
print("\n-- Check the reward function --")
for a in range(2):
    print(' - reward for action <', action_names[a], '> - ')
    print(R[a,:])

(9, 18, 18)

-- Check the transition function --
transition matrix for action < water_1 > (normalized).
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 